import { Router } from "express";
import { adminRoutes } from "../modules/admin/admin.routes.js";
import { aiRoutes } from "../modules/ai/ai.routes.js";
import { accessibilityRoutes } from "../modules/users/accessibility.routes.js";
import { authRoutes } from "../modules/auth/auth.routes.js";
import { assignmentsRoutes } from "../modules/curriculum/assignments.routes.js";
import { badgesRoutes } from "../modules/gamification/badges.routes.js";
import { checklistsRoutes } from "../modules/curriculum/checklists.routes.js";
import { collaborationRoutes } from "../modules/collaboration/collaboration.routes.js";
import { announcementsRoutes } from "../modules/notifications/announcements.routes.js";
import { assessmentsRoutes } from "../modules/assessments/assessments.routes.js";
import { attemptsRoutes } from "../modules/assessments/attempts.routes.js";
import { externalRoutes } from "../modules/ai/external.routes.js";
import { eventsRoutes } from "../modules/notifications/events.routes.js";
import { attendanceRoutes } from "../modules/study/attendance.routes.js";
import { leaderboardRoutes } from "../modules/gamification/leaderboard.routes.js";
import { learningPathRoutes } from "../modules/curriculum/learning-path.routes.js";
import { lessonsRoutes } from "../modules/curriculum/lessons.routes.js";
import { modulesRoutes } from "../modules/curriculum/modules.routes.js";
import { notesRoutes } from "../modules/study/notes.routes.js";
import { onboardingRoutes } from "../modules/users/onboarding.routes.js";
import { parentRoutes } from "../modules/parents/parent.routes.js";
import { progressRoutes } from "../modules/progress/progress.routes.js";
import { quizzesRoutes } from "../modules/quizzes/quizzes.routes.js";
import { resourcesRoutes } from "../modules/curriculum/resources.routes.js";
import { searchRoutes } from "../modules/search/search.routes.js";
import { studyRoutes } from "../modules/study/study.routes.js";
import { subjectsRoutes } from "../modules/curriculum/subjects.routes.js";
import { translateRoutes } from "../modules/ai/translate.routes.js";
import { userModulesRoutes } from "../modules/curriculum/user-modules.routes.js";
import { preferencesRoutes } from "../modules/users/preferences.routes.js";
import { pointsRoutes } from "../modules/gamification/points.routes.js";
import { challengesRoutes } from "../modules/gamification/challenges.routes.js";
import studentRoutes from "../modules/students/student.routes.js";
import tutorRoutes from "../modules/tutoring/tutor.routes.js";
import parentStudentRoutes from "../modules/parents/parent-student.routes.js";
import moduleAssignmentsRoutes from "../modules/curriculum/module-assignments.routes.js";
import moduleUnlockRoutes from "../modules/curriculum/module-unlock.routes.js";
import progressRbacRoutes from "../modules/progress/progress-rbac.routes.js";
import quizzesRbacRoutes from "../modules/quizzes/quizzes-rbac.routes.js";
import { questionBankRoutes } from "../modules/questions/question-bank.routes.js";
import { curriculumRoutes } from "../modules/curriculum/curriculum.routes.js";
import { nscPapersRoutes } from "../modules/nsc-papers/nsc-papers.routes.js";
import { messagingRoutes } from "../modules/collaboration/messaging.routes.js";
import { timetableRoutes } from "../modules/study/timetable.routes.js";
import { analyticsRoutes } from "../modules/admin/analytics.routes.js";
import { educationRoutes } from "../modules/admin/education.routes.js";
import { subjectResourcesRoutes } from "../modules/curriculum/subject-resources.routes.js";
import { notificationsRoutes } from "../modules/notifications/notifications.routes.js";

const router = Router();

router.use("/auth", authRoutes);
router.use("/onboarding", onboardingRoutes);
router.use("/user-modules", userModulesRoutes);
router.use("/subjects", subjectsRoutes);
router.use("/modules", modulesRoutes);
router.use("/lessons", lessonsRoutes);
router.use("/assignments", assignmentsRoutes);
router.use("/resources", resourcesRoutes);
router.use("/quizzes", quizzesRoutes);
router.use("/assessments", assessmentsRoutes);
router.use("/attempts", attemptsRoutes);
router.use("/checklists", checklistsRoutes);
router.use("/badges", badgesRoutes);
router.use("/ai", aiRoutes);
router.use("/study", studyRoutes);
router.use("/announcements", announcementsRoutes);
router.use("/events", eventsRoutes);
router.use("/attendance", attendanceRoutes);
router.use("/progress", progressRoutes);
router.use("/search", searchRoutes);
router.use("/admin", adminRoutes);
router.use("/notes", notesRoutes);
router.use("/learning-path", learningPathRoutes);
router.use("/leaderboard", leaderboardRoutes);
router.use("/accessibility", accessibilityRoutes);
router.use("/external", externalRoutes);
router.use("/collaboration", collaborationRoutes);
router.use("/translate", translateRoutes);
router.use("/parent", parentRoutes);
router.use("/preferences", preferencesRoutes);
router.use("/points", pointsRoutes);
router.use("/challenges", challengesRoutes);
router.use("/student", studentRoutes);
router.use("/tutor", tutorRoutes);
router.use("/question-bank", questionBankRoutes);
router.use("/curriculum", curriculumRoutes);
router.use("/nsc-papers", nscPapersRoutes);
router.use("/messages", messagingRoutes);
router.use("/timetable", timetableRoutes);
router.use("/analytics", analyticsRoutes);
router.use("/education", educationRoutes);
router.use("/subject-resources", subjectResourcesRoutes);
router.use("/notifications", notificationsRoutes);

// RBAC-enabled routes (these routers already define their full paths, e.g. `/parents/...`)
// so we mount them at the API root to avoid double-prefixing `/api/api/...`.
router.use(parentStudentRoutes);
router.use(moduleAssignmentsRoutes);
router.use(moduleUnlockRoutes);
router.use(progressRbacRoutes);
router.use(quizzesRbacRoutes);

export { router };
